[versions]
# Library Info
lib-group-id = "io.github.bugdog24"
lib-version = "0.0.14-alpha09"

# kotlin
kotlin = "2.2.20"
coroutine = "1.10.2"
datetime = "0.7.1-0.6.x-compat"

# serialization
serialization = "1.9.0"

# okio
okio = "3.16.2"

# test
mockk = "1.14.5"
truth = "1.4.4"

# Ktlint
ktlint = "13.0.0"

[libraries]
# kotlin
coroutine = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

# serialization
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
serialization-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "serialization" }

# okio
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

# test
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-coroutine-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutine" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[bundles]
test = ["kotlin-test", "kotlin-junit", "kotlin-coroutine-test", "truth", "mockk"]

[plugins]
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
