[versions]
# Library Info
lib-group-id = "io.github.bugdog24"
lib-version = "0.0.2-alpha05"

# kotlin
kotlin = "2.1.20"
coroutine = "1.10.2"
serialization = "1.9.0"
datetime = "0.7.1-0.6.x-compat"

# test
mockk = "1.14.5"
truth = "1.4.4"

[libraries]
# kotlin
coroutine = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

# test
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-coroutine-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutine" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[bundles]
test = ["kotlin-test", "kotlin-junit", "kotlin-coroutine-test", "truth", "mockk"]

[plugins]
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
